### PR TITLE
Ignite, Spread, Puddle, FIRE

### PR DESCRIPTION
**Pull request by SolarPH**
Changed the entirety of the bullet incendiary flow.

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
I haven't been able to get on my computer all day, and I still can't find the merge button on mobile.

**Comment by SolarPH** [comment]
Oof.

If you have chrome on mobile, get on desktop view. It was on the three
dots, then scroll down a bit, then Desktop Mode checkbox. Dunno about other
mobile browsers tho

**Comment by MEEPofFaith** [comment]
I was on chrom...

**Comment by MEEPofFaith** [comment]
Wait, I can't find it on computer either.
But I can find it on my v2 page to merge my bit into master...

**Comment by MEEPofFaith** [comment]
image
All I see is this instead of the merge button.

**Comment by MEEPofFaith** [comment]
I'm tempted to just copy/paste, but at the same time, I want the collaborator part at the top for you.

**Comment by MEEPofFaith** [comment]
oh

**Pull request closed without merging**
